config/routes.rb
Ladecibelle::Application.routes.draw do
  
  get "page/notrebiere"

  get "page/leconcetp"

  get "page/nosmusique"

  get "page/lej9"

  get "page/contact"

  

  resources :commands

  resources :clients

  root :to => 'page#home'

  resources :produits

  resources :command_details_produits

  resources :services

  resources :command_details_services

end

app/models/command_details_produit.rb
class CommandDetailsProduit < ActiveRecord::Base
  attr_accessible :id_command, :id_service, :prix, :quantite
end

app/controllers/command_details_produits_controller.rb
class CommandDetailsProduitsController < ApplicationController
  # GET /command_details_produits
  # GET /command_details_produits.json
  def index
    @command_details_produits = CommandDetailsProduit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @command_details_produits }
    end
  end

  # GET /command_details_produits/1
  # GET /command_details_produits/1.json
  def show
    @command_details_produit = CommandDetailsProduit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @command_details_produit }
    end
  end

  # GET /command_details_produits/new
  # GET /command_details_produits/new.json
  def new
    @command_details_produit = CommandDetailsProduit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @command_details_produit }
    end
  end

  # GET /command_details_produits/1/edit
  def edit
    @command_details_produit = CommandDetailsProduit.find(params[:id])
  end

  # POST /command_details_produits
  # POST /command_details_produits.json
  def create
    @command_details_produit = CommandDetailsProduit.new(params[:command_details_produit])

    respond_to do |format|
      if @command_details_produit.save
        format.html { redirect_to @command_details_produit, notice: 'Command details produit was successfully created.' }
        format.json { render json: @command_details_produit, status: :created, location: @command_details_produit }
      else
        format.html { render action: "new" }
        format.json { render json: @command_details_produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /command_details_produits/1
  # PUT /command_details_produits/1.json
  def update
    @command_details_produit = CommandDetailsProduit.find(params[:id])

    respond_to do |format|
      if @command_details_produit.update_attributes(params[:command_details_produit])
        format.html { redirect_to @command_details_produit, notice: 'Command details produit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @command_details_produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /command_details_produits/1
  # DELETE /command_details_produits/1.json
  def destroy
    @command_details_produit = CommandDetailsProduit.find(params[:id])
    @command_details_produit.destroy

    respond_to do |format|
      format.html { redirect_to command_details_produits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/command_details_produits_helper.rb
module CommandDetailsProduitsHelper
end

app/views/command_details_produits/_form.html.erb
<%= form_for(@command_details_produit) do |f| %>
  <% if @command_details_produit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@command_details_produit.errors.count, "error") %> prohibited this command_details_produit from being saved:</h2>

      <ul>
      <% @command_details_produit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_command %><br />
    <%= f.text_area :id_command %>
  </div>
  <div class="field">
    <%= f.label :id_service %><br />
    <%= f.text_area :id_service %>
  </div>
  <div class="field">
    <%= f.label :quantite %><br />
    <%= f.number_field :quantite %>
  </div>
  <div class="field">
    <%= f.label :prix %><br />
    <%= f.text_field :prix %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/command_details_produits/edit.html.erb
<h1>Editing command_details_produit</h1>

<%= render 'form' %>

<%= link_to 'Show', @command_details_produit %> |
<%= link_to 'Back', command_details_produits_path %>

app/views/command_details_produits/index.html.erb
<h1>Listing command_details_produits</h1>

<table>
  <tr>
    <th>Id command</th>
    <th>Id service</th>
    <th>Quantite</th>
    <th>Prix</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @command_details_produits.each do |command_details_produit| %>
  <tr>
    <td><%= command_details_produit.id_command %></td>
    <td><%= command_details_produit.id_service %></td>
    <td><%= command_details_produit.quantite %></td>
    <td><%= command_details_produit.prix %></td>
    <td><%= link_to 'Show', command_details_produit %></td>
    <td><%= link_to 'Edit', edit_command_details_produit_path(command_details_produit) %></td>
    <td><%= link_to 'Destroy', command_details_produit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Command details produit', new_command_details_produit_path %>

app/views/command_details_produits/new.html.erb
<h1>New command_details_produit</h1>

<%= render 'form' %>

<%= link_to 'Back', command_details_produits_path %>

app/views/command_details_produits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id command:</b>
  <%= @command_details_produit.id_command %>
</p>

<p>
  <b>Id service:</b>
  <%= @command_details_produit.id_service %>
</p>

<p>
  <b>Quantite:</b>
  <%= @command_details_produit.quantite %>
</p>

<p>
  <b>Prix:</b>
  <%= @command_details_produit.prix %>
</p>


<%= link_to 'Edit', edit_command_details_produit_path(@command_details_produit) %> |
<%= link_to 'Back', command_details_produits_path %>