config/routes.rb
Ladecibelle::Application.routes.draw do
  
  get "page/notrebiere"

  get "page/leconcetp"

  get "page/nosmusique"

  get "page/lej9"

  get "page/contact"

  

  resources :commands

  resources :clients

  root :to => 'page#home'

  resources :produits

  resources :command_details_produits

  resources :services

  resources :command_details_services

end

app/models/command_details_service.rb
class CommandDetailsService < ActiveRecord::Base
  attr_accessible :id_command, :id_service, :prix, :quantite
end

app/controllers/command_details_services_controller.rb
class CommandDetailsServicesController < ApplicationController
  # GET /command_details_services
  # GET /command_details_services.json
  def index
    @command_details_services = CommandDetailsService.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @command_details_services }
    end
  end

  # GET /command_details_services/1
  # GET /command_details_services/1.json
  def show
    @command_details_service = CommandDetailsService.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @command_details_service }
    end
  end

  # GET /command_details_services/new
  # GET /command_details_services/new.json
  def new
    @command_details_service = CommandDetailsService.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @command_details_service }
    end
  end

  # GET /command_details_services/1/edit
  def edit
    @command_details_service = CommandDetailsService.find(params[:id])
  end

  # POST /command_details_services
  # POST /command_details_services.json
  def create
    @command_details_service = CommandDetailsService.new(params[:command_details_service])

    respond_to do |format|
      if @command_details_service.save
        format.html { redirect_to @command_details_service, notice: 'Command details service was successfully created.' }
        format.json { render json: @command_details_service, status: :created, location: @command_details_service }
      else
        format.html { render action: "new" }
        format.json { render json: @command_details_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /command_details_services/1
  # PUT /command_details_services/1.json
  def update
    @command_details_service = CommandDetailsService.find(params[:id])

    respond_to do |format|
      if @command_details_service.update_attributes(params[:command_details_service])
        format.html { redirect_to @command_details_service, notice: 'Command details service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @command_details_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /command_details_services/1
  # DELETE /command_details_services/1.json
  def destroy
    @command_details_service = CommandDetailsService.find(params[:id])
    @command_details_service.destroy

    respond_to do |format|
      format.html { redirect_to command_details_services_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/command_details_services_helper.rb
module CommandDetailsServicesHelper
end

app/views/command_details_services/_form.html.erb
<%= form_for(@command_details_service) do |f| %>
  <% if @command_details_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@command_details_service.errors.count, "error") %> prohibited this command_details_service from being saved:</h2>

      <ul>
      <% @command_details_service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_command %><br />
    <%= f.text_field :id_command %>
  </div>
  <div class="field">
    <%= f.label :id_service %><br />
    <%= f.text_field :id_service %>
  </div>
  <div class="field">
    <%= f.label :quantite %><br />
    <%= f.number_field :quantite %>
  </div>
  <div class="field">
    <%= f.label :prix %><br />
    <%= f.text_field :prix %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/command_details_services/edit.html.erb
<h1>Editing command_details_service</h1>

<%= render 'form' %>

<%= link_to 'Show', @command_details_service %> |
<%= link_to 'Back', command_details_services_path %>

app/views/command_details_services/index.html.erb
<h1>Listing command_details_services</h1>

<table>
  <tr>
    <th>Id command</th>
    <th>Id service</th>
    <th>Quantite</th>
    <th>Prix</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @command_details_services.each do |command_details_service| %>
  <tr>
    <td><%= command_details_service.id_command %></td>
    <td><%= command_details_service.id_service %></td>
    <td><%= command_details_service.quantite %></td>
    <td><%= command_details_service.prix %></td>
    <td><%= link_to 'Show', command_details_service %></td>
    <td><%= link_to 'Edit', edit_command_details_service_path(command_details_service) %></td>
    <td><%= link_to 'Destroy', command_details_service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Command details service', new_command_details_service_path %>

app/views/command_details_services/new.html.erb
<h1>New command_details_service</h1>

<%= render 'form' %>

<%= link_to 'Back', command_details_services_path %>

app/views/command_details_services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id command:</b>
  <%= @command_details_service.id_command %>
</p>

<p>
  <b>Id service:</b>
  <%= @command_details_service.id_service %>
</p>

<p>
  <b>Quantite:</b>
  <%= @command_details_service.quantite %>
</p>

<p>
  <b>Prix:</b>
  <%= @command_details_service.prix %>
</p>


<%= link_to 'Edit', edit_command_details_service_path(@command_details_service) %> |
<%= link_to 'Back', command_details_services_path %>