config/routes.rb
Ladecibelle::Application.routes.draw do
  
  get "page/notrebiere"

  get "page/leconcetp"

  get "page/nosmusique"

  get "page/lej9"

  get "page/contact"

  

  resources :commands

  resources :clients

  root :to => 'page#home'

  resources :produits

  resources :command_details_produits

  resources :services

  resources :command_details_services

end

app/models/command.rb
class Command < ActiveRecord::Base

  attr_accessible  :dates_paiement, :prix_ttc
   belongs_to :client
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  # GET /commands
  # GET /commands.json
  def index
    @commands = Command.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @commands }
    end
  end

  # GET /commands/1
  # GET /commands/1.json
  def show
    @command = Command.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @command }
    end
  end

  # GET /commands/new
  # GET /commands/new.json
  def new
    @command = Command.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @command }
    end
  end

  # GET /commands/1/edit
  def edit
    @command = Command.find(params[:id])
  end

  # POST /commands
  # POST /commands.json
  def create
    @command = Command.new(params[:command])

    respond_to do |format|
      if @command.save
        format.html { redirect_to @command, notice: 'Command was successfully created.' }
        format.json { render json: @command, status: :created, location: @command }
      else
        format.html { render action: "new" }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /commands/1
  # PUT /commands/1.json
  def update
    @command = Command.find(params[:id])

    respond_to do |format|
      if @command.update_attributes(params[:command])
        format.html { redirect_to @command, notice: 'Command was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1
  # DELETE /commands/1.json
  def destroy
    @command = Command.find(params[:id])
    @command.destroy

    respond_to do |format|
      format.html { redirect_to commands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/_form.html.erb
<%= form_for(@command) do |f| %>
  <% if @command.errors.any? %>
    <div id="error_explanation">
      <h1><%= pluralize(@command.errors.count, "error") %> prohibited this command from being saved:</h1>

      <ul>
      <% @command.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <div class="field">
    <%= f.label :client_id %><br />
    <%= f.number_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :dates_paiement %><br />
    <%= f.date_select :dates_paiement %>
  </div>
  <div class="field">
    <%= f.label :prix_ttc %><br />
    <%= f.text_field :prix_ttc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/commands/edit.html.erb
<h1>Editing command</h1>

<%= render 'form' %>

<%= link_to 'Show', @command %> |
<%= link_to 'Back', commands_path %>

app/views/commands/index.html.erb
<h5>Listing commands</h5>

<table>
  <tr>
    <th>Client</th>
    <th>Dates paiement</th>
    <th>Prix ttc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @commands.each do |command| %>
  <tr>
    <td><%= command.client_id %></td>
    <td><%= command.dates_paiement %></td>
    <td><%= command.prix_ttc %></td>
    <td><%= link_to 'Show', command %></td>
    <td><%= link_to 'Edit', edit_command_path(command) %></td>
    <td><%= link_to 'Destroy', command, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Command', new_command_path %>

app/views/commands/new.html.erb
<h1>New command</h1>

<%= render 'form' %>

<%= link_to 'Back', commands_path %>

app/views/commands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Client:</b>
  <%= @command.client_id %>
</p>

<p>
  <b>Dates paiement:</b>
  <%= @command.dates_paiement %>
</p>

<p>
  <b>Prix ttc:</b>
  <%= @command.prix_ttc %>
</p>


<%= link_to 'Edit', edit_command_path(@command) %> |
<%= link_to 'Back', commands_path %>